--CREATE SCHEMA IF NOT EXISTS test;
--SET SCHEMA test;

CREATE TABLE IF NOT EXISTS MESSAGE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    SENDER varchar(150) NOT NULL,
    SUBJECT varchar(150) NOT NULL,
    BODY varchar(500) NOT NULL,

    CREATED DATE,
    PRIMARY KEY (ID)
);
