version: '3.8'
services:
  db:
    image: mariadb:11.2
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: db
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpassword
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: DB
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80
    depends_on:
      - db
    networks:
      - network

volumes:
  mysql-data:

networks:
  adminer-network: